name 'motd-attribute'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures motd-attribute'
long_description 'Installs/Configures motd-attribute'
version '0.1.0'
