name 'apache'
maintainer 'kevivmatrix'
maintainer_email 'vivekpatna52@gmail.com'
license 'all_rights'
description 'Installs/Configures apache'
long_description 'Installs/Configures apache'
version '0.1.0'
