name 'enterprise'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures enterprise'
long_description 'Installs/Configures enterprise'
version '0.1.0'
